In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# this is done without preprocessing the images.


In [ ]:
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),r
    MaxPooling2D(2,2),

    Flatten(),

    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(4, activation='softmax')  # 4 classes
])

c:\Users\dhdar\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rescale = 1./255,
    validation_split=0.2
)
train_data = datagen.flow_from_directory(
    "Training",
    target_size = (224,224),
    batch_size = 32,
    class_mode = "categorical",
    subset = "training"
)

val_data = datagen.flow_from_directory(
    "Training",
    target_size = (224,224),
    batch_size = 32,
    class_mode = "categorical",
    subset = "validation"
)

Found 4480 images belonging to 4 classes.
Found 1120 images belonging to 4 classes.


In [12]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [13]:
history = model.fit(
    train_data,
    epochs=20,
    validation_data = val_data
)


Epoch 1/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 133s 940ms/step - accuracy: 0.6692 - loss: 0.8224 - val_accuracy: 0.8000 - val_loss: 0.5364
Epoch 2/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 108s 771ms/step - accuracy: 0.8219 - loss: 0.4737 - val_accuracy: 0.8375 - val_loss: 0.4316
Epoch 3/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 104s 739ms/step - accuracy: 0.8730 - loss: 0.3484 - val_accuracy: 0.8732 - val_loss: 0.3464
Epoch 4/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 136s 695ms/step - accuracy: 0.9062 - loss: 0.2497 - val_accuracy: 0.9000 - val_loss: 0.2731
Epoch 5/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 101s 720ms/step - accuracy: 0.9310 - loss: 0.1866 - val_accuracy: 0.9045 - val_loss: 0.2743
Epoch 6/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 99s 705ms/step - accuracy: 0.9525 - loss: 0.1340 - val_accuracy: 0.9170 - val_loss: 0.2625
Epoch 7/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 101s 721ms/step - accuracy: 0.9594 - loss: 0.1175 - val_accuracy: 0.9152 - val_loss: 0.2315
Epoch 8/20
140/140 ━━━━━━━━━━━━━━━━━━━━ 99s 703ms/step - accuracy: 0.9663 - l

In [ ]:
model.save("trained_model.keras")

In [ ]:
from tensorflow.keras.models import load_model

model = load_model("trained_model.keras") 

In [ ]:
datagen_for_testing = ImageDataGenerator(
    rescale = 1./255
)

test_data = datagen_for_testing.flow_from_directory(
    "Testing",
    target_size = (224,224),
    batch_size = 32,
    class_mode ="categorical",
    shuffle=False
)

Found 1600 images belonging to 4 classes.


In [20]:
test_loss, test_accuracy = model.evaluate(test_data)

print("Test Accuracy:", test_accuracy)

50/50 ━━━━━━━━━━━━━━━━━━━━ 19s 371ms/step - accuracy: 0.8750 - loss: 1.2626
Test Accuracy: 0.875


In [22]:
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

# Get predictions
pred_probs = model.predict(test_data)
y_pred = np.argmax(pred_probs, axis=1)

# True labels
y_true = test_data.classes

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
print(cm)

# Detailed report
print(classification_report(y_true, y_pred))


50/50 ━━━━━━━━━━━━━━━━━━━━ 6s 126ms/step
[[288  59  47   6]
 [ 19 349  23   9]
 [  5   2 393   0]
 [ 11  19   0 370]]
              precision    recall  f1-score   support

           0       0.89      0.72      0.80       400
           1       0.81      0.87      0.84       400
           2       0.85      0.98      0.91       400
           3       0.96      0.93      0.94       400

    accuracy                           0.88      1600
   macro avg       0.88      0.88      0.87      1600
weighted avg       0.88      0.88      0.87      1600



In [39]:
from tensorflow.keras.preprocessing import image
import numpy as np

img_path = "t1.jpg"

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)
img_array = img_array / 255.0
img_array = np.expand_dims(img_array, axis=0)


In [ ]:
prediction = model.predict(img_array)
print(prediction)
predicted_index = np.argmax(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)
print(np.__version__)

2.20.0
1.26.4


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout


In [41]:
print(predicted_index)

0
